[0m20:37:00.252205 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d271085ccd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d271076bd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d2712cc2150>]}


============================== 20:37:00.275419 | d5c32a7a-738f-4475-93ba-b023f1128be9 ==============================
[0m20:37:00.275419 [info ] [MainThread]: Running with dbt=1.10.5
[0m20:37:00.278419 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/app/dbt_integrado2', 'debug': 'False', 'warn_error': 'None', 'log_path': '/app/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m20:37:00.383712 [info ] [MainThread]: dbt version: 1.10.5
[0m20:37:00.387505 [info ] [MainThread]: python version: 3.11.13
[0m20:37:00.391596 [info ] [MainThread]: python path: /usr/local/bin/python3.11
[0m20:37:00.394160 [info ] [MainThread]: os info: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m20:37:00.426899 [info ] [MainThread]: Using profiles dir at /app/dbt_integrado2
[0m20:37:00.429261 [info ] [MainThread]: Using profiles.yml file at /app/dbt_integrado2/profiles.yml
[0m20:37:00.432306 [info ] [MainThread]: Using dbt_project.yml file at /app/dbt_project.yml
[0m20:37:00.662832 [info ] [MainThread]: Configuration:
[0m20:37:00.665409 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m20:37:00.668361 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m20:37:00.671246 [info ] [MainThread]: Required dependencies:
[0m20:37:00.673637 [debug] [MainThread]: Executing "git --help"
[0m20:37:00.681664 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m20:37:00.684400 [info ] [MainThread]: Connection test skipped since no profile was found
[0m20:37:00.688426 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:37:00.690746 [info ] [MainThread]: Profile loading failed for the following reason:
Runtime Error
  Could not find profile named 'integrador2'


[0m20:37:00.693111 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH: "git"

[0m20:37:00.698421 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.6476923, "process_in_blocks": "87576", "process_kernel_time": 6.912071, "process_mem_max_rss": "104216", "process_out_blocks": "2088", "process_user_time": 3.487742}
[0m20:37:00.700442 [debug] [MainThread]: Command `dbt debug` failed at 20:37:00.700175 after 0.65 seconds
[0m20:37:00.702259 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d271085c990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d271085de90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d271085c790>]}
[0m20:37:00.704716 [debug] [MainThread]: Flushing usage events
[0m20:37:01.731321 [debug] [MainThread]: An error was encountered while trying to flush usage events
