[0m17:41:07.459575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD690ECF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD4768A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD8A74A50>]}


============================== 17:41:07.465121 | 4a3ee508-ade9-4bf8-8410-5c95d5b7977e ==============================
[0m17:41:07.465121 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:41:07.465744 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'dbt_integrado2', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt deps --project-dir . --profiles-dir dbt_integrado2', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:41:07.466516 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path .\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:41:07.467286 [debug] [MainThread]: Command `dbt deps` failed at 17:41:07.467175 after 0.21 seconds
[0m17:41:07.467605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD8AA5810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD8AB9D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD79138A0>]}
[0m17:41:07.467937 [debug] [MainThread]: Flushing usage events
[0m17:41:08.325889 [debug] [MainThread]: An error was encountered while trying to flush usage events
